export default {
  Base: "/api",
  GenerateToken: {
    Base: "/generatetoken",
    Get: "/",
  },
  Users: {
    Base: "/users",
    Get: "/all",
    GetOne: "/:id",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
    BuyStock: "/buystock",
    Login: "/login",
    Register: "/register",
    Logout: "/logout",
  },
  Stocks: {
    Base: "/stock",
    Get: "/all",
    GetById: "/:id",
    GetByStockName: "/:name",
    GetByShortName: "/shortname/:shortName",
    GetByUnitPrice: "/price/:price",
    GetByDispo: "/dispo/:status",
    Add: "/add",
    Update: "/update",
    Delete: "/delete/:id",
  },
} as const;
